[project]
title = "Walmart Sales Explorer"
version = "0.1.0"
port = 8501
slug = "walmart-sales-explorer"
entrypoint = "script.py"

[branding]
name = "Walmart Sales Explorer"
theme:
  primary_color = "#2F4F4F"
  secondary_color = "#FFFFFF"

[data.Walmart_Sales]
type = "csv"
path = "data/Walmart_Sales.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"